config/routes.rb
Rails.application.routes.draw do
  # Google Anonymous Sessions
  # https://stackoverflow.com/questions/4361994/create-named-routes-for-omniauth-in-rails-3
  get 'auth/:provider/callback', to: 'anonymous_sessions#create', as: :oauth_callback
  # get 'auth/:provider', as: :oauth
  get 'auth/failure', to: redirect('/')
  resources :anonymous_sessions, only: [:create]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # https://github.com/plataformatec/devise/wiki/How-To:-Change-Default-Sign_up---Registration-Path-with-Custom-Path
  devise_for :users, :controllers => {:registrations => "users/registrations"}


  # https://stackoverflow.com/questions/14416234/devise-redirect-automatically-from-root-url-if-signed-in
  authenticated :user do
    get 'site/show', to: 'site#show', as: 'show'
    # get 'categories/:id', to: 'categories#show', as: 'categories'
    post 'site/search'
    get 'site/main'
    root to: "site#main"
  end
  get 'site/home'
  get 'site/main', redirect: 'site/home'
  get 'userinfo/profile', to: 'userinfo#profile', as: 'profile'
  get 'userinfo/postuser.:user_id', to: 'userinfo#postuser', as: 'postuser'
  get 'userinfo/edit_profile', to: 'userinfo#edit_profile', as: 'edit_profile'
  patch 'userinfo/update_profile/:user_id', to: 'userinfo#update_profile', as: 'update_profile'
  root to: 'site#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ----------------  RESTful STYLE ROUTING  -----------

  resources :items do
    resources :comments, only: [:create, :update, :destroy]
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end

  # For best-in-place https://stackoverflow.com/questions/23814255/nomethoderror-for-best-in-place-gem
  # Also for other js actions
  resources :comments, only: [:update, :destroy]
  resources :reports, only: [:destroy]
  resources :bid_infos, only: [:update, :destroy] # will created via nested actions

  # https://stackoverflow.com/questions/5246767/sti-one-controller
  resources :bid_items, :controller => :items, :type => "BidItem" do
    resources :comments, only: [:create, :update, :destroy]
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end
  #
  resources :non_bid_items, :controller => :items, :type => "NonBidItem" do
    resources :comments, only: [:create, :update, :destroy]
    # resources :images
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end

end

app/models/bid_info.rb
class BidInfo < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_presence_of :bid_price
end

app/controllers/bid_infos_controller.rb
class BidInfosController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_bid_info, only: [:update, :destroy]
  before_action :set_item, only: [:create]

  # POST /bid_infos
  # POST /bid_infos.json
  def create
    @bid_info = BidInfo.new(bid_info_params)
    @bid_info.item = @item
    @bid_info.user = current_user
    @item.winning_bid = @bid_info
    if @bid_info.bid_price.nil?
      return redirect_to item_path(@item), flash: {error: 'Please enter some price'}
    end
    output = @item.validates_new_bid_price(@bid_info.bid_price)
    if output[:status]
      if @bid_info.save && @item.save
        respond_to do |format|
          format.html {redirect_to item_path(@item), notice: output[:msg]}
          format.json {render :show, status: :created, location: item_path(@item)}
        end
      else
        respond_to do |format|
          format.html {redirect_to item_path(@item), flash: {error: 'Unable to process entity'}}
          format.json {render json: @bid_info.errors, status: :unprocessable_entity}
        end
      end
    else
      respond_to do |format|
        format.html {redirect_to item_path(@item), flash: {error: output[:msg]}}
        format.json {render json: @bid_info.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /bid_infos/1
  # PATCH/PUT /bid_infos/1.json
  def update
    @item = @bid_info.item
    @bid_info.assign_attributes(bid_info_params)
    @item.winning_bid = @bid_info
    if @bid_info.bid_price.nil?
      # if not return it will go to the next line
      return redirect_to item_path(@item), flash: {error: 'Please enter some price'}
    end
    output = @item.validates_new_bid_price(@bid_info.bid_price)
    if output[:status]
      if @bid_info.save && @item.save
        respond_to do |format|
          format.html {redirect_to item_path(@item), notice: output[:msg]}
          format.json {render :show, status: :created, location: @item}
        end
      else
        puts @item.errors.full_messages
        respond_to do |format|
          format.html {redirect_to item_path(@item), flash: {error: 'Unable to process entity'}}
          format.json {render json: @bid_info.errors, status: :unprocessable_entity}
        end
      end
    else
      respond_to do |format|
        format.html {redirect_to item_path(@item), flash: {error: output[:msg]}}
        format.json {render json: @bid_info.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /bid_infos/1
  # DELETE /bid_infos/1.json
  def destroy
    @item = @bid_info.item
    del_id = @bid_info.id
    @bid_info.destroy
    if @item.winner_id == del_id
      # The bid_info that we are going to delete
      # is the current winning bid, so we need to update
      @item.update_winning_bid
      @item.save
    end

    respond_to do |format|
      format.html {redirect_to item_path(@item), notice: 'Bid was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bid_info
    @bid_info = BidInfo.find(params[:id])
  end

  def set_item
    if params[:type] == "BidItem"
      @item = BidItem.find(params[:bid_item_id])
    elsif params[:type] == "NonBidItem"
      @item = NonBidItem.find(params[:non_bid_item_id])
    else
      @item = Item.find(params[:item_id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bid_info_params
    params.require(:bid_info).permit(:bid_price)
  end
end

app/helpers/bid_infos_helper.rb
module BidInfosHelper
end

app/views/bid_infos/_form.html.erb
<%= simple_form_for(bid_info) do |f| %>
    <%= f.error_notification %>

    <div class="form-group">
      <%= label_tag 'Raise new bid price' %> <%= f.text_field :bid_price %>
      <%= f.button :submit, data: {disable_with: 'Bidding Expires'}%>
    </div>
<% end %>

app/views/bid_infos/_show_bid_info_table.html.erb
<!-- TODO add padding-left paddding-right -->
<table class="table table-condensed">
  <thead>
  <tr>
    <th>Username</th>
    <th>Bid Price</th>
    <th>Bid Time (UTC +07:00)</th>
  </tr>
  </thead>
  <tbody>
  <% #Current winner should be in green %>
  <% if @item.bid_infos.size > 0%>
      <% @bid_infos.each do |bi| %>
      <tr class=<%= (bi.id == @item.winner_id) ? "success" : "default" %>>
        <td><%= link_to bi.user.username, postuser_path(bi.user) %></td>
        <td><%= bi.bid_price %></td>
        <td><%= bi.updated_at.localtime %> UTC </td>
        <% if current_user.id == bi.user.id %>
        <td>
          <%= link_to bi, method: :delete, :data => {:confirm => 'Are you sure?'} do %>
              <i class="glyphicon glyphicon-remove pull-right" style="color: red"></i>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
  <% else %>
      <tr>
        <td colspan="3"> <p align="center">No Bidding</p> </td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/bid_infos/edit.html.erb
<h1>Editing Bid Info</h1>

<%= render 'form', bid_info: @bid_info %>

<%= link_to 'Show', @bid_info %> |
<%= link_to 'Back', bid_infos_path %>

app/views/bid_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bid Infos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bid_infos.each do |bid_info| %>
      <tr>
        <td><%= link_to 'Show', bid_info %></td>
        <td><%= link_to 'Edit', edit_bid_info_path(bid_info) %></td>
        <td><%= link_to 'Destroy', bid_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid Info', new_bid_info_path %>

app/views/bid_infos/new.html.erb
<h1>New Bid Info</h1>

<%= render 'form', bid_info: @bid_info %>

<%= link_to 'Back', bid_infos_path %>

app/views/bid_infos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bid_info_path(@bid_info) %> |
<%= link_to 'Back', bid_infos_path %>