config/routes.rb
Rails.application.routes.draw do
  # Google Anonymous Sessions
  # https://stackoverflow.com/questions/4361994/create-named-routes-for-omniauth-in-rails-3
  get 'auth/:provider/callback', to: 'anonymous_sessions#create', as: :oauth_callback
  # get 'auth/:provider', as: :oauth
  get 'auth/failure', to: redirect('/')
  resources :anonymous_sessions, only: [:create]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # https://github.com/plataformatec/devise/wiki/How-To:-Change-Default-Sign_up---Registration-Path-with-Custom-Path
  devise_for :users, :controllers => {:registrations => "users/registrations"}


  # https://stackoverflow.com/questions/14416234/devise-redirect-automatically-from-root-url-if-signed-in
  authenticated :user do
    get 'site/show', to: 'site#show', as: 'show'
    # get 'categories/:id', to: 'categories#show', as: 'categories'
    post 'site/search'
    get 'site/main'
    root to: "site#main"
  end
  get 'site/home'
  get 'site/main', redirect: 'site/home'
  get 'userinfo/profile', to: 'userinfo#profile', as: 'profile'
  get 'userinfo/postuser.:user_id', to: 'userinfo#postuser', as: 'postuser'
  get 'userinfo/edit_profile', to: 'userinfo#edit_profile', as: 'edit_profile'
  patch 'userinfo/update_profile/:user_id', to: 'userinfo#update_profile', as: 'update_profile'
  root to: 'site#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ----------------  RESTful STYLE ROUTING  -----------

  resources :items do
    resources :comments, only: [:create, :update, :destroy]
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end

  # For best-in-place https://stackoverflow.com/questions/23814255/nomethoderror-for-best-in-place-gem
  # Also for other js actions
  resources :comments, only: [:update, :destroy]
  resources :reports, only: [:destroy]
  resources :bid_infos, only: [:update, :destroy] # will created via nested actions

  # https://stackoverflow.com/questions/5246767/sti-one-controller
  resources :bid_items, :controller => :items, :type => "BidItem" do
    resources :comments, only: [:create, :update, :destroy]
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end
  #
  resources :non_bid_items, :controller => :items, :type => "NonBidItem" do
    resources :comments, only: [:create, :update, :destroy]
    # resources :images
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
  has_many :likes, as: :likeable # to get likes; c.likes
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images
  has_paper_trail
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_item, only: [:create]
  before_action :set_comment, only: [:update, :destroy]

  # GET /comments
  # GET /comments.json
  # def index
  #   @comments = Comment.all
  # end
  #
  # # GET /comments/1
  # # GET /comments/1.json
  # def show
  # end
  #
  # # GET /comments/new
  # def new
  #   @comment = Comment.new
  # end

  # GET /comments/1/edit
  # def edit
  # end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @item.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html {redirect_to item_path(@item), notice: 'Comment was successfully created.'}
        # format.json { render :show, status: :created, location: @comment }
      else
        format.html {redirect_to root_path, error: 'Failed to create comment'}
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html {redirect_to item_path(@item), notice: 'Comment was successfully updated.'}
        format.json {render :show, status: :ok, location: @comment}
      else
        format.html {render :edit}
        format.json {render json: @comment.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to item_path(@item), notice: 'Comment was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def set_item
    if params[:type] == "BidItem"
      @item = BidItem.find(params[:bid_item_id])
    elsif params[:type] == "NonBidItem"
      @item = NonBidItem.find(params[:non_bid_item_id])
    else
      @item = Item.find(params[:item_id])
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
    unless @comment.nil?
      @item = @comment.item
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_show.html.erb
<!-- template credit https://bootsnipp.com/snippets/featured/user-comment-example -->
<!-- Fixed instance var name -->
<div class="row">
  <div class="col-sm-1">
    <div class="thumbnail">
      <% if comment.user.avatar.exists? %>
          <%= image_tag comment.user.avatar.url(:thumb), class: "img-responsive user-photo" %>
      <% else %>
          <%= image_tag image_path("missing.png"), class: "img-responsive user-photo" %>
      <% end %>
    </div><!-- /thumbnail -->
  </div><!-- /col-sm-1 -->

  <div class="col-sm-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong><%= link_to comment.user.username, postuser_path(comment.user) %></strong>
        <span class="text-muted pull-right"><%= distance_of_time_in_words_to_now(comment.created_at) %></span>
        <% if current_user.id == comment.user.id %>
            <%= link_to comment, method: :delete, :data => {:confirm => 'Are you sure?'} do %>
                <i class="glyphicon glyphicon-remove pull-right" style="color: red"><strong>Delete</strong></i>
            <% end %>
        <% end %>
      </div>
      <div class="panel-body">
        <div>
          <%= best_in_place_if (current_user.id == comment.user.id), comment, :body,
                               :as => :textarea, :ok_button => 'Edit', ok_button_class: 'btn btn-primary',
                               :cancel_button => 'Cancel', cancel_button_class: 'btn' %>
        </div>
        <div class="pull-right">
          <% if current_user.id == comment.user.id %>
              <p style="color: #b9b9b9">double click to edit ...</p>
          <% end %>
        </div>
      </div><!-- /panel-body -->
    </div><!-- /panel panel-default -->
  </div><!-- /col-sm-5 -->
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>