config/routes.rb
Rails.application.routes.draw do
  # Google Anonymous Sessions
  # https://stackoverflow.com/questions/4361994/create-named-routes-for-omniauth-in-rails-3
  get 'auth/:provider/callback', to: 'anonymous_sessions#create', as: :oauth_callback
  # get 'auth/:provider', as: :oauth
  get 'auth/failure', to: redirect('/')
  resources :anonymous_sessions, only: [:create]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # https://github.com/plataformatec/devise/wiki/How-To:-Change-Default-Sign_up---Registration-Path-with-Custom-Path
  devise_for :users, :controllers => {:registrations => "users/registrations"}


  # https://stackoverflow.com/questions/14416234/devise-redirect-automatically-from-root-url-if-signed-in
  authenticated :user do
    get 'site/show', to: 'site#show', as: 'show'
    # get 'categories/:id', to: 'categories#show', as: 'categories'
    post 'site/search'
    get 'site/main'
    root to: "site#main"
  end
  get 'site/home'
  get 'site/main', redirect: 'site/home'
  get 'userinfo/profile', to: 'userinfo#profile', as: 'profile'
  get 'userinfo/postuser.:user_id', to: 'userinfo#postuser', as: 'postuser'
  get 'userinfo/edit_profile', to: 'userinfo#edit_profile', as: 'edit_profile'
  patch 'userinfo/update_profile/:user_id', to: 'userinfo#update_profile', as: 'update_profile'
  root to: 'site#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ----------------  RESTful STYLE ROUTING  -----------

  resources :items do
    resources :comments, only: [:create, :update, :destroy]
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end

  # For best-in-place https://stackoverflow.com/questions/23814255/nomethoderror-for-best-in-place-gem
  # Also for other js actions
  resources :comments, only: [:update, :destroy]
  resources :reports, only: [:destroy]
  resources :bid_infos, only: [:update, :destroy] # will created via nested actions

  # https://stackoverflow.com/questions/5246767/sti-one-controller
  resources :bid_items, :controller => :items, :type => "BidItem" do
    resources :comments, only: [:create, :update, :destroy]
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end
  #
  resources :non_bid_items, :controller => :items, :type => "NonBidItem" do
    resources :comments, only: [:create, :update, :destroy]
    # resources :images
    resources :bid_infos, only: [:create, :update, :destroy]
    resources :reports, only: [:create]
    put "like", to: "items#like"
    put "unlike", to: "items#unlike"
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  # https://stackoverflow.com/questions/36227578/reference-with-custom-name-and-foreign-key
  belongs_to :winning_bid, foreign_key: :winner_id, class_name: 'BidInfo', optional: true
  has_many :likes, as: :likeable
  has_many :report_from_others, as: :reportable, class_name: 'Report'
  validates_presence_of :type
  # https://stackoverflow.com/questions/27002946/rails-validates-presense-not-validating-on-boolean
  validates_inclusion_of :sell_type, in: [true, false]
  # https://stackoverflow.com/questions/1550688/how-do-i-create-a-default-value-for-attributes-in-rails-activerecords-model
  before_save :default_values
  has_paper_trail

  has_many :bid_infos, dependent: :destroy

  has_many :images, as: :imageable, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :images,
                                :reject_if => proc {|attributes| attributes['content'].blank?},
                                :allow_destroy => true
  validates_presence_of :type
  ITEM_TYPES = ['BidItem', 'NonBidItem']

  def liked_by(user)
    self.likes << Like.new(user: user)
    self.save
  end

  def unliked_by(user)
    l = self.likes.find_by_user_id(user.id)
    if !l.nil?
      l.delete
      self.save
    else
      false
    end
  end

  def is_liked_by?(user)
    !self.likes.find_by_user_id(user.id).nil?
  end

  def is_reported_by?(user)
    !self.report_from_others.find_by_user_id(user.id).nil?
  end

  def contains_bid_info_by?(user)
    !self.bid_infos.find_by_user_id(user.id).nil?
  end

  def get_bid_info_by(user)
    self.bid_infos.find_by_user_id(user.id)
  end

  def is_bid_item?
    self.type == "BidItem"
  end

  def is_non_bid_item?
    self.type == "NonBidItem"
  end

  def price_msg
    if self.is_bid_item?
      if self.sell_type
        "Minimum Bidding"
      else
        "Maximum Bidding"
      end
    else
      if self.sell_type
        "Selling"
      else
        "Requesting"
      end
    end
  end

  def is_bidding_end?
    if self.is_bid_item?
      DateTime.now.utc > self.bid_end_time
    else
      false
    end
  end

  def validates_new_bid_price(bid_price)
    # Returing Hash {status: true/false, msg: 'notice or error' }
    if self.is_bid_item?
      if self.is_bidding_end?
        {status: false, msg: 'Sorry, Bidding Time out !'}
      else
        if self.sell_type
          # SELL BIDDING
          # Start from the current price as minimum price
          if self.bid_infos.size > 0
            if bid_price > self.bid_infos.order("bid_price DESC").first.bid_price
              {status: true, msg: 'Successfully raise a new bid'}
            else
              {status: false, msg: 'Sorry, your biding price is too low'}
            end
          else
            if bid_price > self.product_price
              {status: true, msg: 'Successfully raise a new bid'}
            else
              {status: false, msg: 'Sorry, your biding price is lower than minimum bidding price'}
            end
          end
        else
          # BUY BIDDING
          if self.bid_infos.size > 0
            if bid_price < self.bid_infos.order("bid_price ASC").first.bid_price
              {status: true, msg: 'Successfully raise a new bid'}
            else
              {status: false, msg: 'Sorry, your biding price is too high (Buying Item)'}
            end
          else
            if bid_price < self.product_price
              {status: true, msg: 'Successfully raise a new bid'}
            else
              {status: false, msg: 'Sorry, your biding price is higher than expected price (Buying Item)'}
            end
          end
        end
      end
    else
      {status: false, msg: 'This is not bidable Item'}
    end
  end

  def update_winning_bid
    if self.bid_infos.size > 0
      if self.sell_type
        self.winning_bid = self.bid_infos.order("bid_price DESC").first
      else
        self.winning_bid = self.bid_infos.order("bid_price ASC").first
      end
    else
      self.winning_bid = nil
    end
  end

  def sell_type_str
    self.sell_type ? "Sell" : "Buy"
  end

  private
  def default_values
    self.view_count ||= 0
    self.product_price ||= 0
    self.close_deal ||= false
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :set_current_category
  # GET /items
  # GET /items.json
  def index
    redirect_to root_path
    # we will not show it here
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item.view_count += 1

    if @item.is_bid_item? && @item.is_bidding_end? && !@item.close_deal
      @item.close_deal = true
    end
    @item.save
    @comments = Comment.where(item_id: @item).order("created_at ASC")
    @report = Report.new
    @report.reportable_id = @item.id
    @report.reportable_type = "Item"
    if @item.is_bid_item?
      @current_user_bid_info = @item.get_bid_info_by current_user
      if @item.bid_infos.size > 0
        if @item.sell_type
          @bid_infos = @item.bid_infos.order("bid_price DESC")
        else
          @bid_infos = @item.bid_infos.order("bid_price ASC")
        end
      end
    end
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.type = params[:type]
    @item.images.build
    @item.bid_end_time = DateTime.now
  end

  # GET /items/1/edit
  def edit
    if @item.is_bidding_end?
      unless @item.close_deal
        @item.close_deal = true
        @item.save
      end
      return redirect_to item_path(@item), flash: {error: 'Bidding Has already End, Cannot edit any details anymore'}
    end
    if @item.close_deal
      return redirect_to item_path(@item), flash: {error: 'This Item deal has already been closed'}
    end

    @hide_bid_deadline = (@item.type == "NonBidItem")
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @item.view_count = 0
    @item.close_deal = false
    @item.sell_type = (params[:sell_type] == "Sell")
    @item.bid_end_time = convert_local_to_utc(params[:bid_end_time]) unless params[:bid_end_time].nil?
    respond_to do |format|
      if @item.save
        format.html {redirect_to root_path, notice: 'Item was successfully created.'}
        format.json {render :show, status: :created, location: @item}
      else
        format.html {render :new}
        format.json {render json: @item.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.is_bidding_end?
      unless @item.close_deal
        @item.close_deal = true
        @item.save
      end
      return redirect_to item_path(@item), flash: {error: 'Bidding Has already End, Cannot edit any details anymore'}
    end
    if @item.close_deal
      return redirect_to item_path(@item), flash: {error: 'This Item deal has already been closed'}
    end
    @item.assign_attributes(item_params)
    @item.sell_type = (params[:sell_type] == "Sell")
    @item.bid_end_time = convert_local_to_utc(params[:bid_end_time]) unless params[:bid_end_time].nil?
    respond_to do |format|
      # if @item.update(item_params)
      if @item.save
        format.html {redirect_to item_path(@item), notice: 'Item was successfully updated.'}
        format.json {render :show, status: :ok, location: @item}
      else
        format.html {render :edit}
        format.json {render json: @item.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html {redirect_to root_path, notice: 'Item was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def like
    @item.liked_by current_user

    if request.xhr?
      render json: { count: @item.likes.size, id: @item.id }
    else
      redirect_to item_path(@item)
    end
  end

  def unlike
    @item.unliked_by current_user

    if request.xhr?
      render json: { count: @item.likes.size, id: @item.id }
    else
      redirect_to item_path(@item)
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    if params[:id]
      @item = Item.find(params[:id])
    elsif params[:item_id]
      @item = Item.find(params[:item_id])
    end
  end

  def set_current_category
    @current_categories = Category.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    # http://api.rubyonrails.org/classes/ActiveRecord/Base.html#label-Single+table+inheritance
    if params[:type] == "BidItem"
      params.require(:bid_item).permit(:title, :body, :type,
                                       :category_id, :product_name,
                                       :product_desc, :product_ref_url, :close_deal,
                                       :product_price, images_attributes: [:content, :_destroy, :id])
    elsif params[:type] == "NonBidItem"
      params.require(:non_bid_item).permit(:title, :body, :type,
                                           :category_id, :product_name,
                                           :product_desc, :product_ref_url, :close_deal,
                                           :product_price, images_attributes: [:content, :_destroy, :id])
    else
      params.require(:item).permit(:title, :body, :type,
                                   :category_id, :product_name,
                                   :product_desc, :product_ref_url, :close_deal,
                                   :product_price, images_attributes: [:content, :_destroy, :id])
    end
  end

  def convert_local_to_utc(t_local)
    tmp = DateTime.strptime(t_local, '%m/%d/%Y %I:%M %p').to_formatted_s(:db)
    Time.parse(tmp).utc
  end

  def convert_utc_to_local(t_utc)
    t_utc.localtime
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item_bid_info_form.html.erb
<%= simple_form_for [item, item.bid_infos.build] do |f| %>
    <%= f.error_notification %>

    <div class="form-group">
      <%= label_tag 'Raise new bid price' %> <%= f.text_field :bid_price %> <%= f.button :submit %>
    </div>
<% end %>

app/views/items/_item_comment_form.html.erb
<div class="row">
  <div class="col-sm-1">
    <div class="thumbnail">
      <% if current_user.avatar.exists? %>
          <%= image_tag current_user.avatar.url(:thumb), class: "img-responsive user-photo" %>
      <% else %>
          <%= image_tag image_path("missing.png"), class: "img-responsive user-photo" %>
      <% end %>
    </div><!-- /thumbnail -->
  </div><!-- /col-sm-1 -->

  <div class="col-sm-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong><%= current_user.username %></strong>
      </div>
      <div class="panel-body">
        <!-- Nested attributes form -->
        <%= simple_form_for [item, item.comments.build] do |f| %>
            <div>
              <%= f.text_area :body, placeholder: 'comment something ...', cols: 50, rows: 5 %>
            </div>
            <div class="pull-right">
              <%= f.button :submit %>
            </div>
        <% end %>
      </div><!-- /panel-body -->
    </div><!-- /panel panel-default -->
  </div><!-- /col-sm-5 -->
</div>

app/views/items/_item_list_table_backup.html.erb
<!-- IN: table_id (string), items (active record array of items) -->

<table class="table" style="margin: 0px auto;" id=<%= table_id %>>
  <tbody>
  <% count = 1 %>
  <% items.each do |item| %>
      <br>
      <th scope="row"><%= count %>
      <td>
        <strong><h5><%= image_tag item.user.avatar.url(:thumb), class: "user" %>
          <!-- https://stackoverflow.com/questions/37579880/linking-to-profile-page-by-username-on-ruby -->
          <%= link_to item.user.username, postuser_path(item.user.id) if item.user %>
        </strong>&nbsp;&nbsp; <b>>>>>></b>&nbsp;&nbsp;
        <strong><%= item.product_name %></br>
        </strong></h5>
        <h5><b>Price &nbsp;<%= item.product_price %></b></h5></br></br>
        <% if item.images.present? %>
            <div>
              <%= render 'images/images_gallery', images: item.images, style: 'width: 100px; height: 100px' %>
            </div>
        <% end %>
      </td>
      <td><span class="label label-default pull-right marginBottom10"><%= item.sell_type ? "SELL" : "BUY" %></span></td>
      <td><%= link_to 'view', item_path(item) %></td>

      </tr>
      <% count += 1 %>
  <% end %>
  </tbody>
</table>

app/views/items/_item_list_table_index.html.erb
<!-- IN: table_id (string), items (active record array of items) -->
<table class="table-striped" id=<%= table_id %>>
  <% count = 1 %>
  <tbody>
  <% items.each do |item| %>
      <tr>
        <td>
          <div class="row">
            <div class="col-xs-12 col-sm-3 col-md-3">
              <% if item.images.size > 0 %>
                  <%= link_to image_tag(item.images[0].content.url(:medium), class: "img-responsive img-box img-thumbnail"), item_path(item) %>
              <% else %>
                  <%= link_to image_tag(image_path("item_missing.png"), class: "img-responsive img-box img-thumbnail"), item_path(item) %>
              <% end %>
            </div>
            <div class="col-xs-12 col-sm-9 col-md-9">
              <div class="pull-right">
                <% if item.is_non_bid_item? %>
                    <% if !item.close_deal %>
                        <span class="label label-success pull-right marginBottom10">On Dealing</span>
                    <% else %>
                        <span class="label label-danger pull-right marginBottom10">Deal Closed</span>
                    <% end %>
                <% else %>
                    <% if !item.is_bidding_end? %>
                        <span class="label label-success pull-right marginBottom10">On Dealing</span>
                    <% else %>
                        <span class="label label-danger pull-right marginBottom10">Deal Closed</span>
                    <% end %>
                <% end %>
                <span class="label label-primary pull-right marginBottom10 marginRight1"><%= item.type %></span>
                <span class="label label-default pull-right marginBottom10"><%= item.sell_type ? "SELL" : "BUY" %></span>
              </div>

              <div class="list-group">
                <div class="list-group-item">
                  <div class="row-picture">
                      <%= link_to image_tag(item.user.avatar.url(:thumb), class: "circle img-thumbnail img-box", alt: "sintret"), postuser_path(item.user) %>
                  </div>
                  <div class="row-content">
                    <div class="list-group-item-heading">
                      <%= link_to item.title, item_path(item) %>
                    </div>
                    <small>
                      <i class="glyphicon glyphicon-time"></i> <%= distance_of_time_in_words_to_now(item.created_at) %>
                      ago by
                      <%= link_to item.user.username, postuser_path(item.user) %>
                      <br>
                      <i class="glyphicon glyphicon glyphicon-thumbs-up"></i><span><a style="color: green;"> Liked by <%= item.likes.count %>
                      users </a></span>
                    </small>
                  </div>
                </div>
              </div>
              <p style="font-size:20px"><strong> Product: <%= item.product_name %></strong></p>
              <p style="font-size:20px"><strong> <%= item.price_msg %> Price: <%= item.product_price %> ฿</strong></p>

            </div>
          </div>
        </td>
      </tr>
      <% count += 1 %>
  <% end %>
  </tbody>

</table>

app/views/items/_item_report_modal_form.html.erb
<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>
<div class="modal fade" id="report_post_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Report This Item</h4>
      </div>
      <div class="modal-body">
        <%= render 'reports/report_modal_form', reportable: @item %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
//    $('#report_submit').click(function() {
//        $('#report_post_modal').modal('toggle');
//        alert('Report sent!');
//        // refresh this page to turn off
//        // TODO -- We need to get the real feedback from reports controller
//        location.reload();
//    });
</script>

app/views/items/_items_list_table.html.erb
<!-- IN: table_id (string), items (active record array of items) -->

<table class="table" id=<%= table_id %>>
  <thead>
  <tr>

    <th scope="col">#</th>
    <th scope="col">Product Name</th>
    <th scope="col">Title</th>
    <th scope="col">Cat</th>
    <th scope="col">Sell/Buy</th>
    <th scope="col">Type</th>


    <th scope="col">Author</th>
    <th scope="col">Price</th>
  </tr>
  </thead>

  <tbody>
  <% count = 1 %>
  <% items.each do |item| %>
      <tr>
        <th scope="row"><%= count %></th>
        <td><%= item.product_name %></td>
        <td><%= item.title %></td>
        <td><%= item.category.name %></td>
        <td><%= item.sell_type ? 'Sell' : 'Buy' %></td>
        <td><%= item.is_bid_item? ? 'Bidding' : 'NonBidding' %></td>
        <td><strong>

          <!-- https://stackoverflow.com/questions/37579880/linking-to-profile-page-by-username-on-ruby -->
          <%= link_to item.user.username, postuser_path(item.user.id) if item.user %>


        </strong></td>

        <td><%= item.product_price %></td>
        <td><%= link_to 'view', item_path(item) %></td>

      </tr>
      <% count += 1 %>
  <% end %>
  </tbody>
</table>

app/views/items/_show_table.html.erb
<div class="col-md-10">
  <table class="table-striped table-bordered table-responsive">
    <tbody>
    <tr>
      <th scope="row">Title</th>
      <td><%= @item.title %></td>
    </tr>
    <tr>
      <th scope="row">Type</th>
      <td><%= @item.type %></td>
    </tr>
    <tr>
      <th scope="row">Body</th>
      <td><%= @item.body %></td>
    </tr>

    <tr>
      <th scope="row">Owner</th>
      <td><%= @item.user.first_name + @item.user.last_name %></td>
    </tr>
    <tr>
      <th scope="row">Contact</th>
      <td><%= @item.user.cell_phone_no %></td>
    </tr>

    <tr>
      <th scope="row">Category</th>
      <td><%= @item.category.name %></td>
    </tr>

    <tr>
      <th scope="row">Product Name</th>
      <td><%= @item.product_name %></td>
    </tr>

    <tr>
      <th scope="row">Product Descrption</th>
      <td><%= @item.product_desc %></td>
    </tr>

    <tr>
      <th scope="row">Product Refernce URL</th>
      <td><%= @item.product_ref_url ? "[NONE]" : link_to(@item.product_ref_url, @item.product_ref_url)  %></td>
    </tr>

    <tr>
      <th scope="row">Product <%= @item.price_msg %> Price</th>
      <td><%= @item.product_price %></td>
    </tr>

    </tbody>
  </table>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Back', item_path(@item) %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', root_path %>

app/views/items/show.html.erb
<!-- report popup http://ericlondon.com/2014/03/13/rails-4-submit-modal-form-via-ajax-and-render-js-response-as-table-row.html -->
<div class="row">
</div>
</br>
<div class="row" style="margin-right: 100px">
  <div class="col-xs-4">
    <%= render 'images/images_gallery', images: @item.images %>
  </div>
  <div class="col-xs-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 style="font-weight: bold"><%= @item.title %>
          <% if !@item.close_deal %>
              <span class="label label-success pull-right marginBottom10">On Dealing</span>
          <% else %>
              <span class="label label-danger pull-right marginBottom10">Deal Closed</span>
          <% end %>

          <span class="label label-primary pull-right marginBottom10 marginRight1"><%= @item.type %></span>
          <span class="label label-default pull-right marginBottom10"><%= @item.sell_type ? "SELL" : "BUY" %></span>
        </h3>

      </div>
      <div class="panel-body">
        <!--Boostrap template: https://bootsnipp.com/snippets/featured/blog-post-cms -->
        <div class="col-md-20 blogShort">
          <!-- https://stackoverflow.com/questions/27476734/ruby-image-tag-printing-entire-record-of-image-onscreen -->
          <% #- @item.images.each do |img| %>
          <% # image_tag(img.content.url(:thumb), class: 'pull-left img-responsive thumb margin10 img-thumbnail') %>
          <% # end %>
          <%= render 'show_table' %>
          <% if @item.user_id == current_user.id %>
              <div class="pull-right marginBottom10 btn-group btn-group-sm">

                <%= link_to 'Edit Item', edit_item_path(@item), class: "btn btn-warning" %>
                <!-- <= link_to 'CLOSE THIS DEAL', '#', class: "btn btn-blog", onclick: 'item_js.closeDeal();' > -->
                <!-- https://stackoverflow.com/questions/16668949/how-to-add-confirm-message-with-link-to-ruby-on-rails -->
                <% if !@item.close_deal && @item.is_non_bid_item? %>
                    <%= link_to 'Close This Deal', item_path({id: @item.id, item: {close_deal: true}}),
                                :data => {:confirm => 'Are you sure?'}, method: :put, class: "btn" %>
                <% end %>

                <%= link_to 'Delete Item', item_path(@item), method: :delete,
                            :data => {:confirm => 'Are you sure?'},
                            class: "btn btn-danger" %>
              </div>
          <% else %>
              <!-- For owner : can report -->
              <% unless @item.is_reported_by?(current_user) %>
                  <%# Added Bootstrap data modal attribute %>
                  <%= render 'item_report_modal_form' %>
                  <%= link_to 'Report This Post', '#report_post_modal', 'data-toggle' => 'modal' %>
              <% end %>

          <% end %>
        </div>
      </div>
      <div>
        <i class="glyphicon glyphicon glyphicon-thumbs-up"></i>
        <span class="likes-count" data-id="<%= @item.id %>">
        <%= @item.likes.size %>
      </span>
        users like this
        <% if @item.is_liked_by? current_user %>
            <%= link_to "Unlike", item_unlike_path(@item),
                        class: 'like', method: :put, remote: true,
                        data: {toggle_text: 'Like', toggle_href: item_like_path(@item), id: @item.id} %>
        <% else %>
            <%= link_to "Like", item_like_path(@item),
                        class: 'like', method: :put, remote: true,
                        data: {toggle_text: 'Unlike', toggle_href: item_unlike_path(@item), id: @item.id} %>
        <% end %>
      </div>
    </div>
    <div class="pull-right">
      <p>views: <%= @item.view_count %></p>
    </div>
  </div>
</div>
</br>
<div class="row">
  <div class="col-xs-12">
    <%= render 'images/image_gallery_selector', images: @item.images %>
  </div>
</div>

<% if @item.is_bid_item? %>
    <div class="row">
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-4">
                <h3 style="font-weight: bold">Bidding Table</h3>
              </div>
              <div class="col-xs-offset-6 col-xs-2">
                Deadline <%= @item.bid_end_time.localtime.strftime("%B %d, %Y %I:%M:%S") %>
              </div>
            </div>
          </div>
          <div class="panel-body">

            <div class="row" style="margin-bottom: 20px; margin-top: 20px">
              <div class="col-md-offset-2 col-md-2">
                <strong>Time to Bidding Deadline</strong>
              </div>
              <div class="col-md-4 countdown" data-until="<%= @item.bid_end_time.localtime.to_s %>" data-outformat="%D-%H:%M:%S"></div>

            </div>

            <div class="row">
              <div class="col-xs-12">
                <%= render 'bid_infos/show_bid_info_table' %>
              </div>
            </div>
            <div class="container" id="bid_info_form">
              <% if !@item.is_bidding_end? && !@item.close_deal %>
                  <% if @current_user_bid_info.nil? %>
                      <% # new %>
                      <%= render 'item_bid_info_form', item: @item %>
                  <% else %>
                      <% # edit %>
                      <%= render 'bid_infos/form', bid_info: @current_user_bid_info %>
                  <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>


<% end %>


<h2> Comments </h2>
<div class="row">
  <!-- TODO EDIT and Delete -->
  <% @comments.each do |c| %>
      <%= render 'comments/show', comment: c %>
  <% end %>
</div>

<div class="row">
  <%= render 'item_comment_form', item: @item %>
</div>


<%= link_to 'Back', root_path %>